# Generated by Django 4.1 on 2022-08-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JopPosting',
            new_name='JobPosting',
        ),
    ]
