# Generated by Django 4.1 on 2022-08-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_jopposting_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.company'),
        ),
    ]
